### ISSUE TITLE
Create an action to automatically build develop and publish npm:next version

### ISSUE THREAD

**Issue by ShravanSunder** [scaffold-eth/eth-hooks#65]

**Comment by ShravanSunder** [comment]
look into semantic release
```
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: test-lint-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore node modules cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Release
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release
```

https://github.com/semantic-release/semantic-release
